databases:
  - name: vapor-todo-db
    databaseName: vapor_database
    user: vapor_user
    plan: free
    region: oregon

services:
  # Vapor Todo API Service
  - type: web
    name: vapor-todo-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vapor-todo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ISSUER
        value: vapor-todo-api
      - key: JWT_AUDIENCE
        value: vapor-todo-users
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.com,https://admin.your-domain.com
